#include "ZFUIListAdapterBasic.h"

ZF_NAMESPACE_GLOBAL_BEGIN

ZFOBJECT_REGISTER(ZFUIListAdapterBasicParam)

ZFOBJECT_REGISTER(ZFUIListAdapterBasic)

ZFEVENT_REGISTER(ZFUIListAdapterBasic, ListCellCount)
ZFEVENT_REGISTER(ZFUIListAdapterBasic, ListCellAt)
ZFEVENT_REGISTER(ZFUIListAdapterBasic, ListCellSizeAt)
ZFEVENT_REGISTER(ZFUIListAdapterBasic, ListCellCacheOnAccess)

ZF_NAMESPACE_GLOBAL_END

