
function(zfprojConfigBefore_ZFUIKit_impl projName ZF_SRC_FILES)
    # https://open.oppomobile.com/new/developmentDoc/info?id=13223
    set(FONT_URL "https://openfs.oppomobile.com/open/oop/202410/18/62d51f494591f1a9040d83b597745911.zip")

    message("ZFSDL: font setup begin")
    set(FONT_REPO_FILE "${ZF_ROOT_PATH}/ZF/ZFUIKit_impl/zf3rd/_repo/font.zip")
    set(FONT_REPO_PATH "${ZF_ROOT_PATH}/ZF/ZFUIKit_impl/zf3rd/_repo/font")
    if(NOT EXISTS ${FONT_REPO_FILE})
        zfprojExec("${ZF_ROOT_PATH}/tools/common/file_download" "%${FONT_URL}" "${FONT_REPO_FILE}")
        zfprojExec("${ZF_ROOT_PATH}/tools/common/unzip" "${FONT_REPO_FILE}" "${FONT_REPO_PATH}")
    endif()
    if(${projName} STREQUAL "ZFUIKit_impl")
        install(
            DIRECTORY "${FONT_REPO_PATH}/"
            DESTINATION "${ZF_ROOT_PATH}/_release/cmake/module/ZFUIKit_impl/zfres/ZFUIKit_impl/sys_SDL/font"
            )
    else()
        install(
            DIRECTORY "${FONT_REPO_PATH}/"
            DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/zfres/ZFUIKit_impl/sys_SDL/font"
            )
    endif()
    message("ZFSDL: font setup end")
endfunction()

function(zfprojConfigAfter_ZFUIKit_impl projName)
    target_compile_definitions(${projName} PUBLIC ZF_ENV_FORCE_sys_SDL=1)

    if(NOT TARGET SDL3::SDL3)
        set(SDL_INSTALL ON CACHE BOOL "ZFSDL" FORCE)
        set(SDL_UNIX_CONSOLE_BUILD ON CACHE BOOL "ZFSDL" FORCE)
        add_subdirectory("${ZF_ROOT_PATH}/ZF/ZF_impl/zf3rd/_repo/SDL" ${CMAKE_BINARY_DIR}/SDL)
        target_link_libraries(${projName} PRIVATE SDL3::SDL3)
    endif()

    if(NOT TARGET SDL3_image::SDL3_image)
        set(SDLIMAGE_INSTALL ON CACHE BOOL "ZFSDL" FORCE)
        set(SDLIMAGE_VENDORED ON CACHE BOOL "ZFSDL" FORCE)
        set(SDLIMAGE_AVIF OFF CACHE BOOL "ZFSDL" FORCE)
        set(SDLIMAGE_JXL OFF CACHE BOOL "ZFSDL" FORCE)
        set(SDLIMAGE_LBM OFF CACHE BOOL "ZFSDL" FORCE)
        set(SDLIMAGE_PCX OFF CACHE BOOL "ZFSDL" FORCE)
        set(SDLIMAGE_PNM OFF CACHE BOOL "ZFSDL" FORCE)
        set(SDLIMAGE_QOI OFF CACHE BOOL "ZFSDL" FORCE)
        set(SDLIMAGE_TGA OFF CACHE BOOL "ZFSDL" FORCE)
        set(SDLIMAGE_TIF OFF CACHE BOOL "ZFSDL" FORCE)
        set(SDLIMAGE_XCF OFF CACHE BOOL "ZFSDL" FORCE)
        set(SDLIMAGE_XPM OFF CACHE BOOL "ZFSDL" FORCE)
        set(SDLIMAGE_XV OFF CACHE BOOL "ZFSDL" FORCE)
        add_subdirectory("${ZF_ROOT_PATH}/ZF/ZF_impl/zf3rd/_repo/SDL_image" ${CMAKE_BINARY_DIR}/SDL_image)
        target_link_libraries(${projName} PRIVATE SDL3_image::SDL3_image)
    endif()

    if(NOT TARGET SDL3_mixer::SDL3_mixer)
        set(SDLMIXER_INSTALL ON CACHE BOOL "ZFSDL" FORCE)
        set(SDLMIXER_VENDORED ON CACHE BOOL "ZFSDL" FORCE)
        set(SDLMIXER_AIFF OFF CACHE BOOL "ZFSDL" FORCE)
        set(SDLMIXER_WAVE OFF CACHE BOOL "ZFSDL" FORCE)
        set(SDLMIXER_VOC OFF CACHE BOOL "ZFSDL" FORCE)
        set(SDLMIXER_AU OFF CACHE BOOL "ZFSDL" FORCE)
        set(SDLMIXER_FLAC_LIBFLAC OFF CACHE BOOL "ZFSDL" FORCE)
        set(SDLMIXER_FLAC_DRFLAC OFF CACHE BOOL "ZFSDL" FORCE)
        set(SDLMIXER_GME OFF CACHE BOOL "ZFSDL" FORCE)
        set(SDLMIXER_MOD_XMP OFF CACHE BOOL "ZFSDL" FORCE)
        set(SDLMIXER_OPUS OFF CACHE BOOL "ZFSDL" FORCE)
        set(SDLMIXER_VORBIS_STB OFF CACHE BOOL "ZFSDL" FORCE)
        set(SDLMIXER_VORBIS_VORBISFILE OFF CACHE BOOL "ZFSDL" FORCE)
        set(SDLMIXER_VORBIS_TREMOR OFF CACHE BOOL "ZFSDL" FORCE)
        set(SDLMIXER_WAVPACK OFF CACHE BOOL "ZFSDL" FORCE)
        add_subdirectory("${ZF_ROOT_PATH}/ZF/ZF_impl/zf3rd/_repo/SDL_mixer" ${CMAKE_BINARY_DIR}/SDL_mixer)
        target_link_libraries(${projName} PRIVATE SDL3_mixer::SDL3_mixer)
    endif()

    if(NOT TARGET SDL3_ttf::SDL3_ttf)
        set(SDLTTF_INSTALL ON CACHE BOOL "ZFSDL" FORCE)
        set(SDLTTF_VENDORED ON CACHE BOOL "ZFSDL" FORCE)
        add_subdirectory("${ZF_ROOT_PATH}/ZF/ZF_impl/zf3rd/_repo/SDL_ttf" ${CMAKE_BINARY_DIR}/SDL_ttf)
        target_link_libraries(${projName} PRIVATE SDL3_ttf::SDL3_ttf)
    endif()
endfunction()

