
function(zfprojConfigBefore_ZFNet_impl projName ZF_SRC_FILES)
    set(OPENSSL_USE_STATIC_LIBS TRUE)
    find_package(OpenSSL MODULE)
    if(OPENSSL_FOUND)
        include_directories(${OPENSSL_INCLUDE_DIR})
        message("OpenSSL: ${OPENSSL_INCLUDE_DIR} ${OPENSSL_LIBRARIES}")
    else()
        message("OpenSSL: NOT FOUND")
    endif()
endfunction()

function(zfprojConfigAfter_ZFNet_impl projName)
    find_package(OpenSSL MODULE)
    if(OPENSSL_FOUND)
        set_target_properties(${projName} PROPERTIES CXX_STANDARD 11)
        target_compile_options(${projName} PUBLIC -DZF_ENV_HTTPS=1)
        target_link_libraries(${projName} ${OPENSSL_LIBRARIES})
    endif()

    target_compile_definitions(${projName} PUBLIC ZF_ENV_FORCE_sys_SDL=1)

    if(NOT ZFSDL_SDL2)
        set(ZFSDL_SDL2 TRUE)
        add_subdirectory(${ZF_ROOT_PATH}/ZF/ZF_impl/zf3rd/_repo/SDL SDL)
        target_link_libraries(${projName} SDL2::SDL2)
    endif()

    if(NOT ZFSDL_SDL2_net)
        set(ZFSDL_SDL2_net TRUE)
        add_subdirectory(${ZF_ROOT_PATH}/ZF/ZF_impl/zf3rd/_repo/SDL_net SDL_net)
        target_link_libraries(${projName} SDL2_net::SDL2_net)
    endif()
endfunction()

