platform :ios, '12.0'

# zfprojConfig.rb
#     def zfprojConfig_PROJ_NAME(target)
#       target.pod 'xxx'
#     end

def zfprojConfig(target, cwd, type, proj_name)
  if type == 'local'
    path = File.join(cwd, 'zfprojConfig.rb')
  else
    path = File.join(cwd, '../../../../../ZFFramework', type, proj_name, 'zfproj/iOS', proj_name, 'zfprojConfig.rb')
  end
  if File.file?(path)
    require path
    send('zfprojConfig_' + proj_name, self)
  end
end

target '{ZFTT_R_proj_name}' do
  use_frameworks!
  zfprojConfig(self, __dir__, 'local', '{ZFTT_R_proj_name}'){ZFTT_C_lib_require_0}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_lib_name_0}'){ZFTT_CE}{ZFTT_C_lib_require_1}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_lib_name_1}'){ZFTT_CE}{ZFTT_C_lib_require_2}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_lib_name_2}'){ZFTT_CE}{ZFTT_C_lib_require_3}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_lib_name_3}'){ZFTT_CE}{ZFTT_C_lib_require_4}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_lib_name_4}'){ZFTT_CE}{ZFTT_C_lib_require_5}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_lib_name_5}'){ZFTT_CE}{ZFTT_C_lib_require_6}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_lib_name_6}'){ZFTT_CE}{ZFTT_C_lib_require_7}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_lib_name_7}'){ZFTT_CE}{ZFTT_C_lib_require_8}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_lib_name_8}'){ZFTT_CE}{ZFTT_C_lib_require_9}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_lib_name_9}'){ZFTT_CE}{ZFTT_C_lib_require_10}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_lib_name_10}'){ZFTT_CE}{ZFTT_C_lib_require_11}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_lib_name_11}'){ZFTT_CE}{ZFTT_C_lib_require_12}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_lib_name_12}'){ZFTT_CE}{ZFTT_C_lib_require_13}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_lib_name_13}'){ZFTT_CE}{ZFTT_C_lib_require_14}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_lib_name_14}'){ZFTT_CE}{ZFTT_C_lib_require_15}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_lib_name_15}'){ZFTT_CE}{ZFTT_C_lib_require_16}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_lib_name_16}'){ZFTT_CE}{ZFTT_C_lib_require_17}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_lib_name_17}'){ZFTT_CE}{ZFTT_C_lib_require_18}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_lib_name_18}'){ZFTT_CE}{ZFTT_C_lib_require_19}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_lib_name_19}'){ZFTT_CE}{ZFTT_C_lib_require_20}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_lib_name_20}'){ZFTT_CE}{ZFTT_C_lib_require_21}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_lib_name_21}'){ZFTT_CE}{ZFTT_C_lib_require_22}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_lib_name_22}'){ZFTT_CE}{ZFTT_C_lib_require_23}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_lib_name_23}'){ZFTT_CE}{ZFTT_C_lib_require_24}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_lib_name_24}'){ZFTT_CE}{ZFTT_C_lib_require_25}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_lib_name_25}'){ZFTT_CE}{ZFTT_C_lib_require_26}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_lib_name_26}'){ZFTT_CE}{ZFTT_C_lib_require_27}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_lib_name_27}'){ZFTT_CE}{ZFTT_C_lib_require_28}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_lib_name_28}'){ZFTT_CE}{ZFTT_C_lib_require_29}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_lib_name_29}'){ZFTT_CE}{ZFTT_C_lib_require_30}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_lib_name_30}'){ZFTT_CE}{ZFTT_C_lib_require_31}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_lib_name_31}'){ZFTT_CE}{ZFTT_C_impl_require_0}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_impl_name_0}'){ZFTT_CE}{ZFTT_C_impl_require_1}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_impl_name_1}'){ZFTT_CE}{ZFTT_C_impl_require_2}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_impl_name_2}'){ZFTT_CE}{ZFTT_C_impl_require_3}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_impl_name_3}'){ZFTT_CE}{ZFTT_C_impl_require_4}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_impl_name_4}'){ZFTT_CE}{ZFTT_C_impl_require_5}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_impl_name_5}'){ZFTT_CE}{ZFTT_C_impl_require_6}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_impl_name_6}'){ZFTT_CE}{ZFTT_C_impl_require_7}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_impl_name_7}'){ZFTT_CE}{ZFTT_C_impl_require_8}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_impl_name_8}'){ZFTT_CE}{ZFTT_C_impl_require_9}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_impl_name_9}'){ZFTT_CE}{ZFTT_C_impl_require_10}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_impl_name_10}'){ZFTT_CE}{ZFTT_C_impl_require_11}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_impl_name_11}'){ZFTT_CE}{ZFTT_C_impl_require_12}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_impl_name_12}'){ZFTT_CE}{ZFTT_C_impl_require_13}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_impl_name_13}'){ZFTT_CE}{ZFTT_C_impl_require_14}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_impl_name_14}'){ZFTT_CE}{ZFTT_C_impl_require_15}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_impl_name_15}'){ZFTT_CE}{ZFTT_C_impl_require_16}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_impl_name_16}'){ZFTT_CE}{ZFTT_C_impl_require_17}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_impl_name_17}'){ZFTT_CE}{ZFTT_C_impl_require_18}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_impl_name_18}'){ZFTT_CE}{ZFTT_C_impl_require_19}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_impl_name_19}'){ZFTT_CE}{ZFTT_C_impl_require_20}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_impl_name_20}'){ZFTT_CE}{ZFTT_C_impl_require_21}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_impl_name_21}'){ZFTT_CE}{ZFTT_C_impl_require_22}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_impl_name_22}'){ZFTT_CE}{ZFTT_C_impl_require_23}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_impl_name_23}'){ZFTT_CE}{ZFTT_C_impl_require_24}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_impl_name_24}'){ZFTT_CE}{ZFTT_C_impl_require_25}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_impl_name_25}'){ZFTT_CE}{ZFTT_C_impl_require_26}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_impl_name_26}'){ZFTT_CE}{ZFTT_C_impl_require_27}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_impl_name_27}'){ZFTT_CE}{ZFTT_C_impl_require_28}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_impl_name_28}'){ZFTT_CE}{ZFTT_C_impl_require_29}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_impl_name_29}'){ZFTT_CE}{ZFTT_C_impl_require_30}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_impl_name_30}'){ZFTT_CE}{ZFTT_C_impl_require_31}
  zfprojConfig(self, __dir__, 'ZF', '{ZFTT_R_impl_name_31}'){ZFTT_CE}{ZFTT_C_lib_ext_require_0}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_lib_ext_name_0}'){ZFTT_CE}{ZFTT_C_lib_ext_require_1}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_lib_ext_name_1}'){ZFTT_CE}{ZFTT_C_lib_ext_require_2}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_lib_ext_name_2}'){ZFTT_CE}{ZFTT_C_lib_ext_require_3}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_lib_ext_name_3}'){ZFTT_CE}{ZFTT_C_lib_ext_require_4}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_lib_ext_name_4}'){ZFTT_CE}{ZFTT_C_lib_ext_require_5}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_lib_ext_name_5}'){ZFTT_CE}{ZFTT_C_lib_ext_require_6}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_lib_ext_name_6}'){ZFTT_CE}{ZFTT_C_lib_ext_require_7}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_lib_ext_name_7}'){ZFTT_CE}{ZFTT_C_lib_ext_require_8}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_lib_ext_name_8}'){ZFTT_CE}{ZFTT_C_lib_ext_require_9}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_lib_ext_name_9}'){ZFTT_CE}{ZFTT_C_lib_ext_require_10}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_lib_ext_name_10}'){ZFTT_CE}{ZFTT_C_lib_ext_require_11}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_lib_ext_name_11}'){ZFTT_CE}{ZFTT_C_lib_ext_require_12}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_lib_ext_name_12}'){ZFTT_CE}{ZFTT_C_lib_ext_require_13}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_lib_ext_name_13}'){ZFTT_CE}{ZFTT_C_lib_ext_require_14}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_lib_ext_name_14}'){ZFTT_CE}{ZFTT_C_lib_ext_require_15}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_lib_ext_name_15}'){ZFTT_CE}{ZFTT_C_lib_ext_require_16}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_lib_ext_name_16}'){ZFTT_CE}{ZFTT_C_lib_ext_require_17}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_lib_ext_name_17}'){ZFTT_CE}{ZFTT_C_lib_ext_require_18}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_lib_ext_name_18}'){ZFTT_CE}{ZFTT_C_lib_ext_require_19}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_lib_ext_name_19}'){ZFTT_CE}{ZFTT_C_lib_ext_require_20}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_lib_ext_name_20}'){ZFTT_CE}{ZFTT_C_lib_ext_require_21}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_lib_ext_name_21}'){ZFTT_CE}{ZFTT_C_lib_ext_require_22}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_lib_ext_name_22}'){ZFTT_CE}{ZFTT_C_lib_ext_require_23}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_lib_ext_name_23}'){ZFTT_CE}{ZFTT_C_lib_ext_require_24}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_lib_ext_name_24}'){ZFTT_CE}{ZFTT_C_lib_ext_require_25}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_lib_ext_name_25}'){ZFTT_CE}{ZFTT_C_lib_ext_require_26}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_lib_ext_name_26}'){ZFTT_CE}{ZFTT_C_lib_ext_require_27}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_lib_ext_name_27}'){ZFTT_CE}{ZFTT_C_lib_ext_require_28}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_lib_ext_name_28}'){ZFTT_CE}{ZFTT_C_lib_ext_require_29}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_lib_ext_name_29}'){ZFTT_CE}{ZFTT_C_lib_ext_require_30}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_lib_ext_name_30}'){ZFTT_CE}{ZFTT_C_lib_ext_require_31}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_lib_ext_name_31}'){ZFTT_CE}{ZFTT_C_impl_ext_require_0}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_impl_ext_name_0}'){ZFTT_CE}{ZFTT_C_impl_ext_require_1}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_impl_ext_name_1}'){ZFTT_CE}{ZFTT_C_impl_ext_require_2}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_impl_ext_name_2}'){ZFTT_CE}{ZFTT_C_impl_ext_require_3}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_impl_ext_name_3}'){ZFTT_CE}{ZFTT_C_impl_ext_require_4}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_impl_ext_name_4}'){ZFTT_CE}{ZFTT_C_impl_ext_require_5}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_impl_ext_name_5}'){ZFTT_CE}{ZFTT_C_impl_ext_require_6}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_impl_ext_name_6}'){ZFTT_CE}{ZFTT_C_impl_ext_require_7}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_impl_ext_name_7}'){ZFTT_CE}{ZFTT_C_impl_ext_require_8}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_impl_ext_name_8}'){ZFTT_CE}{ZFTT_C_impl_ext_require_9}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_impl_ext_name_9}'){ZFTT_CE}{ZFTT_C_impl_ext_require_10}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_impl_ext_name_10}'){ZFTT_CE}{ZFTT_C_impl_ext_require_11}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_impl_ext_name_11}'){ZFTT_CE}{ZFTT_C_impl_ext_require_12}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_impl_ext_name_12}'){ZFTT_CE}{ZFTT_C_impl_ext_require_13}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_impl_ext_name_13}'){ZFTT_CE}{ZFTT_C_impl_ext_require_14}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_impl_ext_name_14}'){ZFTT_CE}{ZFTT_C_impl_ext_require_15}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_impl_ext_name_15}'){ZFTT_CE}{ZFTT_C_impl_ext_require_16}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_impl_ext_name_16}'){ZFTT_CE}{ZFTT_C_impl_ext_require_17}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_impl_ext_name_17}'){ZFTT_CE}{ZFTT_C_impl_ext_require_18}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_impl_ext_name_18}'){ZFTT_CE}{ZFTT_C_impl_ext_require_19}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_impl_ext_name_19}'){ZFTT_CE}{ZFTT_C_impl_ext_require_20}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_impl_ext_name_20}'){ZFTT_CE}{ZFTT_C_impl_ext_require_21}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_impl_ext_name_21}'){ZFTT_CE}{ZFTT_C_impl_ext_require_22}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_impl_ext_name_22}'){ZFTT_CE}{ZFTT_C_impl_ext_require_23}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_impl_ext_name_23}'){ZFTT_CE}{ZFTT_C_impl_ext_require_24}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_impl_ext_name_24}'){ZFTT_CE}{ZFTT_C_impl_ext_require_25}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_impl_ext_name_25}'){ZFTT_CE}{ZFTT_C_impl_ext_require_26}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_impl_ext_name_26}'){ZFTT_CE}{ZFTT_C_impl_ext_require_27}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_impl_ext_name_27}'){ZFTT_CE}{ZFTT_C_impl_ext_require_28}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_impl_ext_name_28}'){ZFTT_CE}{ZFTT_C_impl_ext_require_29}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_impl_ext_name_29}'){ZFTT_CE}{ZFTT_C_impl_ext_require_30}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_impl_ext_name_30}'){ZFTT_CE}{ZFTT_C_impl_ext_require_31}
  zfprojConfig(self, __dir__, 'ZFModule', '{ZFTT_R_impl_ext_name_31}'){ZFTT_CE}
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end

