#include "ZFCurve_common.h"

ZF_NAMESPACE_GLOBAL_BEGIN

ZFOBJECT_REGISTER(ZFCurveEaseIn)
ZFOBJECT_REGISTER(ZFCurveEaseOut)
ZFOBJECT_REGISTER(ZFCurveEaseInOut)
ZFOBJECT_REGISTER(ZFCurveBounceIn)
ZFOBJECT_REGISTER(ZFCurveBounceOut)
ZFOBJECT_REGISTER(ZFCurveBounceInOut)

ZF_NAMESPACE_GLOBAL_END

