name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ZFAndroidABI: ${{secrets.ZFANDROIDABI}}

    steps:
    - uses: actions/checkout@v3

    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r21e

    - name: ZF build zfproj_with_src
      run: sh ./master/ZF_CI/testbuild/testbuild_Android.sh ZFFramework_test ./demo/zfproj_with_src/Android/ZFFramework_test

    - name: ZF build zfproj
      run: sh ./master/ZF_CI/testbuild/testbuild_Android.sh ZFFramework_test ./demo/zfproj/Android/ZFFramework_test
