name: Android

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    env:
      ZFCI_TOKEN: ${{secrets.ZFCI_TOKEN}}
      ZFAndroidABI: arm64-v8a
      ZF_PROJ_PATH: demo/zfproj
      ZF_PROJ_NAME: ZFFramework_test

    steps:
    - uses: actions/checkout

    - name: Setup JDK
      uses: actions/setup-java
      with:
        java-version: 11
        distribution: temurin

    - name: Setup Android SDK
      uses: android-actions/setup-android

    - name: Setup Android NDK
      uses: nttld/setup-ndk
      with:
        ndk-version: r21e

    - name: ZFSetup
      run: |
        chmod +x ./zfsetup.sh
        ./zfsetup.sh

    - name: ZF build zfproj
      run: |
        chmod +x ../ZFFramework/master/ZF_CI/testbuild/testbuild_Android.sh
        ../ZFFramework/master/ZF_CI/testbuild/testbuild_Android.sh "${ZF_PROJ_NAME}" "${ZF_PROJ_PATH}/Android/${ZF_PROJ_NAME}"

    - name: ZF upload archive
      run: |
        if [ $(basename $(dirname $(git remote get-url origin)) .git) = "ZFFramework" ]; then
        chmod +x ../ZFFramework/master/ZF_CI/upload_app.sh
        ../ZFFramework/master/ZF_CI/upload_app.sh "${ZF_PROJ_PATH}/Android/${ZF_PROJ_NAME}/zfapp/build/outputs/apk/release/zfapp-release.apk" "${ZF_PROJ_NAME}.apk"
        fi

