name: CMake Windows

on:
  push:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    env:
      ZFCI_TOKEN: ${{secrets.ZFCI_TOKEN}}
      ZF_PROJ_PATH: demo/zfproj
      ZF_PROJ_NAME: ZFFramework_test

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSVC cmd
      uses: TheMrMilchmann/setup-msvc-dev@v3
      with:
        export-path-to-vcvarsall: VCVARSALL_PATH
        arch: x64

    - name: get-cmake
      uses: lukka/get-cmake@latest

    - name: Set up NASM
      uses: ilammy/setup-nasm@v1

    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v5

    - name: ZFSetup
      run: |
        Invoke-Expression -Command 'cmd.exe /C ".\\zfsetup.bat"'

    - name: ZF build zfproj
      run: |
        Invoke-Expression -Command 'cmd.exe /C "..\\ZFFramework\\tools\\buildapp\\buildapp_cmake.bat" "${env:ZF_PROJ_NAME}" "${env:ZF_PROJ_PATH}"'

