name: CMake Windows with src

on:
  push:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    env:
      ZFCI_TOKEN: ${{secrets.ZFCI_TOKEN}}
      ZF_PROJ_PATH: demo/zfproj_with_src
      ZF_PROJ_NAME: ZFFramework_test

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSVC cmd
      uses: TheMrMilchmann/setup-msvc-dev@v3
      with:
        export-path-to-vcvarsall: VCVARSALL_PATH
        arch: x64

    - name: get-cmake
      uses: lukka/get-cmake@v3.31.6

    - name: Set up NASM
      uses: ilammy/setup-nasm@v1

    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v5

    - name: ZFSetup
      run: |
        Invoke-Expression -Command 'cmd.exe /C ".\\zfsetup.bat"'

    - name: ZF build zfproj
      run: |
        Invoke-Expression -Command 'cmd.exe /C "..\\ZFFramework\\tools\\buildapp\\buildapp_cmake.bat" "${env:ZF_PROJ_NAME}" "${env:ZF_PROJ_PATH}"'

    - name: ZF zip archive
      uses: vimtor/action-zip@v1.2
      with:
          files: _tmp/cmake/${{env.ZF_PROJ_NAME}}/app/
          dest: _tmp/cmake/${{env.ZF_PROJ_NAME}}/app.zip

    - name: ZF upload archive
      run: |
        if("ZFFramework" -eq [System.IO.Path]::GetDirectoryName(([System.Uri](git remote get-url origin)).AbsolutePath.TrimStart('/'))) {
        Invoke-Expression -Command 'cmd.exe /C "..\\ZFFramework\\master\\ZF_CI\\upload_app.bat" "_tmp\\cmake\\${env:ZF_PROJ_NAME}\\app.zip" "cmake_Windows\\${env:ZF_PROJ_NAME}.src.zip"'
        }

