name: Doxygen

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    env:
      ZFCI_TOKEN: ${{secrets.ZFCI_TOKEN}}

    steps:
    - uses: actions/checkout@v3

    - name: Setup Doxygen
      uses: mattnotmitt/doxygen-action@1.9.4
      with:
        working-directory: master/ZF_docs/Doxygen
        doxyfile-path: ./Doxyfile

    - name: ZFSetup
      run: |
        chmod +x ./zfsetup.sh
        ./zfsetup.sh

    - name: ZF doxygen
      run: |
        chmod +x ../ZFFramework/master/ZF_CI/doc.sh
        ../ZFFramework/master/ZF_CI/doc.sh

