name: Qt Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    env:
      ZFCI_TOKEN: ${{secrets.ZFCI_TOKEN}}
      ZF_PROJ_PATH: demo/zfproj
      ZF_PROJ_NAME: ZFFramework_test

    steps:
    - uses: actions/checkout@v3

    - name: Setup MSVC cmd
      uses: TheMrMilchmann/setup-msvc-dev@v2
      with:
        export-path-to-vcvarsall: VCVARSALL_PATH

    - name: Setup MSVC env
      run: Invoke-Expression -Command 'cmd.exe /C "$env:VCVARSALL_PATH\\vcvarsall.bat"'

    - name: Setup Qt
      uses: jurplel/install-qt-action@v3.0.0
      with:
        host: windows
        target: desktop
        modules: qtwebengine

    - name: ZFSetup
      run: |
        Invoke-Expression -Command 'cmd.exe /C ".\\zfsetup.bat"'

    - name: ZF build zfproj
      run: |
        Invoke-Expression -Command 'cmd.exe /C "..\\ZFFramework\\master\\ZF_CI\\testbuild\\testbuild_Qt_Windows.bat" "$env:ZF_PROJ_NAME" "$env:ZF_PROJ_PATH\\Qt\\$env:ZF_PROJ_NAME"'

